# This is a basic workflow to help you get started with Actions

name: Samples Build CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

#     - name: Install build-essential
#       run: sudo apt-get install build-essential

    # Get the arm-non-eabi-gcc toolchain   
    - name: Install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        # GNU Embedded Toolchain for Arm release name, in the V-YYYY-qZ format (e.g. "9-2019-q4")
        release: # optional
        # Directory to unpack GCC to. Defaults to a temporary directory.
        directory: # optional

    # Get CMake into the environment
    - name: Install cmake 3.17.1
      uses: lukka/get-cmake@v3.17.1

    # Get Ninja into the environment
    - name: Install ninja-build
      uses: seanmiddleditch/gha-setup-ninja@v1
    
    # Prepare the build system
    - name: Prepare build system
      run: cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=./cmake/cortex-m4.cmake -GNinja ./peter_sample

    - name: Compile and link
      run: cmake --build ./build


