# This is a basic workflow to help you get started with Actions

name: threadx_simple_build_docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container: stronglytyped/arm-none-eabi-gcc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install git
      run: sudo add-apt-repository ppa:git-core/ppa && sudo apt-get update -y -q && sudo apt-get install -y -q git

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout sources recursively
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        submodules: true

    # Prepare the build system
    - name: Prepare build system
      run: cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=./cmake/cortex_m4.cmake -GNinja ./threadx_simple

    - name: Compile and link
      run: cmake --build ./build


